### ISSUE TITLE
A built-in serializeToJson

### ISSUE THREAD

**Issue by aberba** [aravindavk/dpq2-serialization#1]
This will remove the dependency on vibe.d for all other frameworks.

**Comment by aravindavk** [comment]
dpq2-serialization doesn't depends on vibe.d (http server), it only depends on `vibe-serialization` library because `dpq2` depends on vibe:data (Ref: https://github.com/denizzzka/dpq2/blob/master/dub.json#L12).

This can be used with other frameworks without any change. Refer [Handy-Httpd example](https://github.com/aravindavk/dpq2-serialization?tab=readme-ov-file#with-handy-httpd) and [Serverino example](https://github.com/aravindavk/dpq2-serialization?tab=readme-ov-file#with-serverino).
